black style windows:
  tags:
    - windows
  script:
    - black --check -S -t py36 .


unit tests windows:
  tags:
    - windows
  script:
    - pip install -r requirements.txt
    - python -m pytest .


#unit tests linux:
#  tags:
#    - linux
#  before_script:
#    - sudo apt-get install -y build-essential
#    - export PATH=~/anaconda3/bin:$PATH
#    - conda --version
#    - source activate pitl
#    - sudo pip install git+https://www.github.com/keras-team/keras-contrib.git
#  script:
#    - echo $CONDA_DEFAULT_ENV
#    - pip install -r requirements.txt
#    - python -m pytest .
#    - conda deactivate
