py3.6 tests osx:
  tags:
    - osx
  script:
    - conda create -n ay36test python=3.6
    - conda activate ay36test
    - python setup.py develop
    - pip install -r requirements/development.txt
    - python -m pytest .
    - conda deactivate
    - conda env remove -n ay36test

py3.7 tests osx:
  tags:
    - osx
  script:
    - conda create -n ay37test python=3.7
    - conda activate ay37test
    - python setup.py develop
    - pip install -r requirements/development.txt
    - python -m pytest .
    - conda deactivate
    - conda env remove -n ay37test

codecov osx:
  tags:
    - osx
  variables:
    CODECOV_TOKEN: "29f2bb89-a5d6-4a0f-a0e8-74724f6a2b6f"
  script:
    - conda create -n codecovenv python=3.7
    - conda activate codecovenv
    - python setup.py develop
    - pip install -r requirements/development.txt
    - pip install pytest-cov codecov
    - pytest --cov=./aydin
    - codecov
    - conda deactivate
    - conda env remove -n codecovenv

black style osx:
  tags:
    - osx
  script:
    - conda create -n blacktest python=3.7
    - conda activate blacktest
    - pip install black
    - black --check -S -t py36 .
    - conda deactivate
    - conda env remove -n blacktest


#unit tests windows:
#  tags:
#    - windows
#  script:
#    - conda info --envs
#    - python setup.py develop
#    - pip install -r requirements/development.txt
#    - python -m pytest .
#
#
#unit tests linux:
#  tags:
#    - linux
#  before_script:
#    - export PATH=~/anaconda3/bin:$PATH
#  script:
#    - conda create -n ay37test python=3.7
#    - source activate ay37test
#    - python setup.py develop
#    - pip install -r requirements/development.txt
#    - python -m pytest .
#    - conda deactivate
#    - conda env remove -n ay37test
