black style windows:
  tags:
    - windows
  script:
    - black --check -S -t py36 .


unit tests windows:
  tags:
    - windows
  script:
    - pip install -r requirements.txt
    - python -m pytest .


unit tests linux:
  tags:
    - linux
  before_script:
    # - sudo apt-get install python-dev
    - export PATH=~/anaconda3/bin:$PATH
    - conda --version
    - conda create --name aydin python=3.6
    - source activate aydin
    - pip install -r requirements.txt
  script:
    - echo $CONDA_DEFAULT_ENV
    - source activate aydin
    - clinfo
    - python -m pytest .
    - conda deactivate
